import os
os.system("pip3 install requests")
os.system("pip3 install beautifulsoup4")
os.system("pip3 install builtwith")
os.system("pip3 install colorama")
os.system("pip3 install urllib3")
os.system("pip3 install social-analyzer")
os.system("pip3 install whois")
os.system("pip3 install droopescan")
os.system("pip3 install python-nmap")
os.system("pip3 install crypto")
os.system("pip3 install pyopenssl")
os.system("pip3 install slither-analyzer")
os.system("pip3 install awscli")
os.system("pip3 install solc-select")