
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-18T15:20:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "68c4f5645d00f3958471e5e2bc360c90f49a4740",
 "version": "2.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
