VERSION_YEAR = 2023
VERSION_MONTH = int('08')
VERSION_DAY = int('16')
VERSION_HOUR = int('21')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202308162116
version_date = '2023/08/16 21:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
