# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lambda_cloud_client import schemas  # noqa: F401


class ErrorCode(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Unique identifier for the type of error
    """
    
    @schemas.classproperty
    def GLOBAL_UNKNOWN(cls):
        return cls("global/unknown")
    
    @schemas.classproperty
    def GLOBAL_INVALIDAPIKEY(cls):
        return cls("global/invalid-api-key")
    
    @schemas.classproperty
    def GLOBAL_ACCOUNTINACTIVE(cls):
        return cls("global/account-inactive")
    
    @schemas.classproperty
    def GLOBAL_INVALIDPARAMETERS(cls):
        return cls("global/invalid-parameters")
    
    @schemas.classproperty
    def GLOBAL_OBJECTDOESNOTEXIST(cls):
        return cls("global/object-does-not-exist")
    
    @schemas.classproperty
    def INSTANCEOPERATIONS_LAUNCH_INSUFFICIENTCAPACITY(cls):
        return cls("instance-operations/launch/insufficient-capacity")
    
    @schemas.classproperty
    def INSTANCEOPERATIONS_LAUNCH_FILESYSTEMINWRONGREGION(cls):
        return cls("instance-operations/launch/file-system-in-wrong-region")
    
    @schemas.classproperty
    def INSTANCEOPERATIONS_LAUNCH_FILESYSTEMSNOTSUPPORTED(cls):
        return cls("instance-operations/launch/file-systems-not-supported")
    
    @schemas.classproperty
    def SSHKEYS_KEYINUSE(cls):
        return cls("ssh-keys/key-in-use")
