from . import decoder

REGISTER = {
    # P00 Product info area: 0x000A to 0x0020 (22W)
        0xA: {"name": "power_rating", "access": "r", "partition": "p00"},
        0xB: {"name": "product_type", "access": "r", "decoder": decoder.decode_product_type, "partition": "p00"},
        0xC: {"length": 8, "name": "product_model", "access": "r", "decoder": decoder.decode_string, "partition": "p00"},
        0x14: {"length": 2, "name": "software_version", "access": "r", "decoder": decoder.decode_version, "partition": "p00"},
        0x16: {"length": 2, "name": "hardware_version", "access": "r", "decoder": decoder.decode_version, "partition": "p00"},
        0x18: {"length": 2, "name": "product_sn", "access": "r", "decoder": decoder.decode_string, "partition": "p00"},
        0x1A: {"name": "controller_address", "access": "r", "partition": "p00"},
        0x1B: {"name": "model_code", "access": "r", "partition": "p00"},
        0x1C: {"length": 2, "name": "rs485_protocol_version", "access": "r", "decoder": decoder.decode_version, "partition": "p00"},
        0x1E: {"length": 2, "name": "date_of_manufacture", "access": "r", "decoder": decoder.decode_datetime, "partition": "p00"},
        0x20: {"name": "production_site_code", "access": "r", "decoder": decoder.decode_site_code, "partition": "p00"},
        0x21: {"length": 20, "name": "software_compilation_time", "access": "r", "decoder": decoder.decode_string, "partition": "p00"},
        0x35: {"length": 20, "name": "product_sn_string", "access": "r", "decoder": decoder.decode_string, "partition": "p00"},
        0x49: {},
    # P01 Controller data area: 0x0100 to 0x0121 (33W)
        0x100: {"name": "battery_level_soc", "access": "r", "unit": "%", "partition": "p01"},
        0x101: {"name": "battery_voltage", "access": "r", "scale": 0.1, "unit": "V", "partition": "p01"},
        0x102: {"name": "charge_current", "access": "r", "scale": 0.1, "unit": "A", "partition": "p01"},
        0x103: {"name": "controller_and_battery_temperature", "access": "r", "unit": "°C", "decoder": decoder.decode_controller_and_battery_temperature, "partition": "p01"},
        0x104: {"name": "load_dc_voltage", "access": "r", "scale": 0.1, "unit": "V", "partition": "p01"},
        0x105: {"name": "load_dc_current", "access": "r", "scale": 0.01, "unit": "A", "partition": "p01"},
        0x106: {"name": "load_dc_power", "access": "r", "unit": "W", "partition": "p01"},
        0x107: {"name": "pv_panel_voltage", "access": "r", "scale": 0.1, "unit": "V", "partition": "p01"},
        0x108: {"name": "pv_panel_current", "access": "r", "scale": 0.1, "unit": "A", "partition": "p01"},
        0x109: {"name": "pv_charge_power", "access": "r", "unit": "W", "partition": "p01"},
        0x10A: {"name": "dc_load_on_off_command", "access": "w", "partition": "p01"},
        0x10B: {"name": "load_and_charge_status", "access": "r", "decoder": decoder.decode_load_and_charge_status, "partition": "p01"},
        0x10C: {"length": 2, "name": "alarm_message", "access": "r", "decoder": decoder.decode_alarm_message, "partition": "p01"},
        0x10E: {"name": "charge_power", "access": "r", "unit": "W", "partition": "p01"},
        0x10F: {},
    # P02 Inverter data area: 0x0200 to 0x023B (59W)
        0x200: {"length": 4, "name": "current_fault_bits", "access": "r", "decoder": decoder.decode_current_fault_bits, "partition": "p02"},
        0x204: {"length": 4, "name": "current_fault_code", "access": "r", "partition": "p02"},
        0x208: {"length": 4},
        0x20C: {"length": 3, "name": "current_time", "access": "rw", "decoder": decoder.decode_datetime, "partition": "p02"},
        0x20F: {},
        0x210: {"name": "machine_state", "access": "r", "decoder": decoder.decode_machine_state, "partition": "p02"},
        0x211: {"name": "password_protection_status_mark", "access": "r", "decoder": decoder.decode_password_protection_status_mark, "partition": "p02"},
        0x212: {"name": "bus_voltage", "access": "r", "scale": 0.1, "unit": "V", "partition": "p02"},
        0x213: {"name": "grid_voltage", "access": "r", "scale": 0.1, "unit": "V", "partition": "p02"},
        0x214: {"name": "grid_current", "access": "r", "scale": 0.1, "unit": "A", "partition": "p02"},
        0x215: {"name": "grid_frequency", "access": "r", "scale": 0.01, "unit": "Hz", "partition": "p02"},
        0x216: {"name": "inverter_voltage", "access": "r", "scale": 0.1, "unit": "V", "partition": "p02"},
        0x217: {"name": "inverter_current", "access": "r", "scale": 0.1, "unit": "A", "partition": "p02"},
        0x218: {"name": "inverter_frequency", "access": "r", "scale": 0.01, "unit": "Hz", "partition": "p02"},
        0x219: {"name": "load_current", "access": "r", "scale": 0.1, "unit": "A", "partition": "p02"},
        0x21A: {"name": "load_pf", "access": "r", "scale": 0.01, "partition": "p02"},
        0x21B: {"name": "load_active_power", "access": "r", "unit": "W", "partition": "p02"},
        0x21C: {"name": "load_apparent_power", "access": "r", "unit": "VA", "partition": "p02"},
        0x21D: {"name": "inverter_dc_component", "access": "r", "unit": "mV", "partition": "p02"},
        0x21E: {"name": "main_charge_current", "access": "r", "scale": 0.1, "unit": "A", "partition": "p02"},
        0x21F: {"name": "load_ratio", "access": "r", "unit": "%", "partition": "p02"},
        0x220: {"name": "heat_sink_a_temperature", "access": "r", "scale": 0.1, "unit": "°C", "partition": "p02"},
        0x221: {"name": "heat_sink_b_temperature", "access": "r", "scale": 0.1, "unit": "°C", "partition": "p02"},
        0x222: {"name": "heat_sink_c_temperature", "access": "r", "scale": 0.1, "unit": "°C", "partition": "p02"},
        0x223: {"name": "ambient_temperature", "access": "r", "scale": 0.1, "unit": "°C", "partition": "p02"},
        0x224: {"name": "pv_buck_current_1", "access": "r", "scale": 0.1, "unit": "A", "partition": "p02"},
        0x225: {"name": "buck_current_2", "access": "r", "scale": 0.1, "unit": "A", "partition": "p02"},
    # P03 Device control area: 0xDF00 to 0xDF1F (32W)
        0xDF00: {"name": "power_on_off_control", "access": "w", "partition": "p03"},
        0xDF01: {"name": "reset_control", "access": "w", "partition": "p03"},
        0xDF02: {"name": "restore_to_default_settings", "access": "w", "partition": "p03"},
        0xDF03: {"name": "clear_current_alarm", "access": "w", "partition": "p03"},
        0xDF04: {"name": "clear_statistics", "access": "w", "partition": "p03"},
        0xDF05: {"name": "clear_history", "access": "w", "partition": "p03"},
        0xDF06: {"length": 2, "name": "firmware_upgrade_command", "access": "w", "partition": "p03"},
        0xDF08: {"name": "sleep_control", "access": "w", "partition": "p03"},
        0xDF09: {"length": 3, "name": "manual_light_up_switch", "access": "w", "partition": "p03"},
        0xDF0C: {"name": "generator_switch_command", "access": "w", "partition": "p03"},
        0xDF0D: {"name": "immediate_equalizing_charge_command", "access": "w", "partition": "p03"},
    # P05 Battery related parameters settings area: 0xE001 to 0x023B (59W)
        0xE000: {},
        0xE001: {"name": "pv_charge_current_setup", "access": "rw", "unit": "A", "partition": "p05"},
        0xE002: {"name": "nominal_battery_capacity", "access": "rw", "unit": "AH", "partition": "p05"},
        0xE003: {"name": "system_voltage_setup", "access": "rw", "unit": "V", "decoder": decoder.decode_system_voltage_setup, "partition": "p05"},
        0xE004: {"name": "battery_type", "access": "rw", "partition": "p05"},
        0xE005: {"name": "over_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE006: {"name": "limited_charge_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE007: {"name": "equalizing_charge_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE008: {"name": "boost_charge_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE009: {"name": "floating_charge_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE00A: {"name": "boost_charge_return_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE00B: {"name": "over_discharge_return_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE00C: {"name": "under_voltage_waring_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE00D: {"name": "over_discharge_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE00E: {"name": "limited_discharge_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE00F: {"name": "charge_discharge_cutoff_soc", "access": "rw", "decoder": decoder.decode_charge_discharge_cutoff_soc, "partition": "p05"},
        0xE010: {"name": "over_discharge_delay_time", "access": "rw", "unit": "second", "partition": "p05"},
        0xE011: {"name": "equalizing_charge_time", "access": "rw", "unit": "minute", "partition": "p05"},
        0xE012: {"name": "boost_charge_time", "access": "rw", "unit": "minute", "partition": "p05"},
        0xE013: {"name": "equalizing_charge_interval", "access": "rw", "unit": "day", "partition": "p05"},
        0xE014: {"name": "temperature_compensation_coefficient", "access": "rw", "unit": "mV/°C/2V", "partition": "p05"},
        0xE015: {"name": "charge_upper_limit_temperature", "access": "rw", "unit": "°C", "partition": "p05"},
        0xE016: {"name": "charge_lower_limit_temperature", "access": "rw", "unit": "°C", "partition": "p05"},
        0xE017: {"name": "discharge_upper_limit_temperature", "access": "rw", "unit": "°C", "partition": "p05"},
        0xE018: {"name": "discharge_lower_limit_temperature", "access": "rw", "unit": "°C", "partition": "p05"},
        0xE019: {"name": "heating_start_temperature", "access": "rw", "unit": "°C", "partition": "p05"},
        0xE01A: {"name": "heating_stop_temperature", "access": "rw", "unit": "°C", "partition": "p05"},
        0xE01B: {"name": "mains_switching_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE01C: {"name": "stop_charging_current", "access": "rw", "scale": 0.1, "unit": "A", "partition": "p05"},
        0xE01D: {"name": "dc_load_working_mode", "access": "rw", "decoder": decoder.decode_dc_load_working_mode, "partition": "p05"},
        0xE01E: {"name": "light_control_delay_time", "access": "rw", "unit": "minute", "partition": "p05"},
        0xE01F: {"name": "light_control_voltage", "access": "rw", "unit": "V", "partition": "p05"},
        0xE020: {"name": "number_of_batteries_connected_in_series", "access": "rw", "partition": "p05"},
        0xE021: {"name": "special_power_control", "access": "rw", "decoder": decoder.decode_special_power_control, "partition": "p05"},
        0xE022: {"name": "inverter_switching_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p05"},
        0xE023: {"name": "equalizing_charge_timeout", "access": "rw", "unit": "minute", "partition": "p05"},
        0xE024: {"name": "lithium_battery_activation_current", "access": "rw", "scale": 0.1, "unit": "A", "partition": "p05"},
        0xE025: {},
    # P07 Inverter parameters user settings area: 0xE200 to 0xE22F (48W)
        0xE200: {"name": "rs485_address_setup", "access": "rw", "partition": "p07"},
        0xE201: {"name": "baud_rate", "access": "rw", "partition": "p07"},
        0xE202: {"name": "user_password_set_value", "access": "w", "partition": "p07"},
        0xE203: {"name": "password_input", "access": "w", "partition": "p07"},
        0xE204: {"name": "output_priority", "access": "rw", "decoder": decoder.decode_output_priority, "partition": "p07"},
        0xE205: {"name": "mains_charge_current_limit", "access": "rw", "scale": 0.1, "unit": "A", "partition": "p07"},
        0xE206: {"name": "equalizing_charge_enable", "access": "rw", "partition": "p07"},
        0xE207: {"name": "eco_threshold", "access": "rw", "unit": "W"},
        0xE208: {"name": "output_voltage", "access": "rw", "scale": 0.1, "unit": "V", "partition": "p07"},
        0xE209: {"name": "output_frequency", "access": "rw", "scale": 0.01, "unit": "Hz", "partition": "p07"},
        0xE20A: {"name": "maximum_charge_current", "access": "rw", "scale": 0.1, "unit": "A", "partition": "p07"},
        0xE20B: {"name": "ac_input_range", "access": "rw", "decoder": decoder.decode_ac_input_range, "partition": "p07"},
        0xE20C: {"name": "eco_mode", "access": "rw", "decoder": decoder.decode_enable_disable, "partition": "p07"},
        0xE20D: {"name": "overload_auto_restart", "access": "rw", "decoder": decoder.decode_enable_disable, "partition": "p07"},
        0xE20E: {"name": "over_temperature_auto_restart", "access": "rw", "decoder": decoder.decode_enable_disable, "partition": "p07"},
        0xE20F: {"name": "charge_priority", "access": "rw", "decoder": decoder.decode_charge_priority, "partition": "p07"},
        0xE210: {"name": "alarm_control", "access": "rw", "decoder": decoder.decode_enable_disable, "partition": "p07"},
        0xE211: {"name": "alarm_enable_when_input_source_interrupted", "access": "rw", "decoder": decoder.decode_enable_disable, "partition": "p07"},
        0xE212: {"name": "overload_bypass_enable", "access": "rw", "decoder": decoder.decode_enable_disable, "partition": "p07"},
        0xE213: {"name": "record_fault_code", "access": "rw", "decoder": decoder.decode_enable_disable, "partition": "p07"},
        0xE214: {"name": "split_phase_transformer", "access": "rw", "decoder": decoder.decode_enable_disable, "partition": "p07"},
        0xE215: {},
    # P08 Power statistics historical data: 0xF000 to 0xF3FF (1023W)
        0xF000: {"length": 7, "name": "pv_power_generation_last_week", "access": "r", "unit": "AH", "partition": "p08"},
        0xF007: {"length": 7, "name": "battery_charge_level_last_week", "access": "r", "unit": "AH", "partition": "p08"},
        0xF00E: {"length": 7, "name": "battery_discharge_level_last_week", "access": "r", "unit": "AH", "partition": "p08"},
        0xF015: {"length": 7, "name": "mains_charge_level_last_week", "access": "r", "unit": "AH", "partition": "p08"},
        0xF01C: {"length": 7, "name": "load_power_consumption_last_week", "access": "r", "scale": 0.1, "unit": "kWh", "partition": "p08"},
        0xF023: {"length": 7, "name": "mains_power_consumption_last_week", "access": "r", "scale": 0.1, "unit": "kWh", "partition": "p08"},
        0xF02A: {"length": 3},
        0xF02D: {"name": "battery_charge_level_today", "access": "r", "unit": "AH", "partition": "p08"},
        0xF02E: {"name": "battery_discharge_level_today", "access": "r", "unit": "AH", "partition": "p08"},
        0xF02F: {"name": "pv_power_generation_today", "access": "r", "unit": "AH", "partition": "p08"},
        0xF030: {"name": "load_power_consumption_today", "access": "r", "scale": 0.1, "unit": "kWh", "partition": "p08"},
        0xF031: {"name": "total_running_days", "access": "r", "unit": "day", "partition": "p08"},
        0xF032: {"name": "total_battery_overdischarge", "access": "r", "partition": "p08"},
        0xF033: {"name": "total_battery_full_charge", "access": "r", "partition": "p08"},
        0xF034: {"length": 2, "name": "battery_charge_accumulated", "access": "r", "unit": "AH", "partition": "p08"},
        0xF036: {"length": 2, "name": "battery_discharge_accumulated", "access": "r", "unit": "AH", "partition": "p08"},
        0xF038: {"length": 2, "name": "pw_power_generation_accumulated", "access": "r", "scale": 0.1, "unit": "kWh", "partition": "p08"},
        0xF03A: {"length": 2, "name": "load_power_accumulated", "access": "r", "scale": 0.1, "unit": "kWh", "partition": "p08"},
        0xF03C: {"name": "mains_charge_today", "access": "r", "unit": "AH", "partition": "p08"},
        0xF03D: {"name": "mains_power_consumption_today", "access": "r", "scale": 0.1, "unit": "kWh", "partition": "p08"},
        0xF03E: {"name": "inverter_working_hours_today", "access": "r", "unit": "minute", "partition": "p08"},
        0xF03F: {"name": "inverter_bypass_hours_today", "access": "r", "unit": "minute", "partition": "p08"},
        0xF040: {"length": 3, "name": "power_on_time", "access": "r", "decoder": decoder.decode_datetime, "partition": "p08"},
        0xF043: {"length": 3, "name": "equalizing_charge_last_completion_time", "access": "r", "decoder": decoder.decode_datetime, "partition": "p08"},
        0xF046: {"length": 2, "name": "mains_charge_accumulated", "access": "r", "scale": 0.1, "unit": "kWh", "partition": "p08"},
        0xF048: {"length": 2, "name": "mains_power_consuption_accumulated", "access": "r", "scale": 0.1, "unit": "kWh", "partition": "p08"},
        0xF04A: {"name": "inverter_working_hours_accumulated", "access": "r", "unit": "hour", "partition": "p08"},
        0xF04B: {"name": "inverter_bypass_hours_accumulated", "access": "r", "unit": "hour", "partition": "p08"},
        0xF04C: {},
        0xF04D: {},
    # P09 Fault history: 0xF800 to 0xFFFF
        0xF800: {"length": 16, "name": "Fault record 0", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF810: {"length": 16, "name": "Fault record 1", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF820: {"length": 16, "name": "Fault record 2", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF830: {"length": 16, "name": "Fault record 3", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF840: {"length": 16, "name": "Fault record 4", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF850: {"length": 16, "name": "Fault record 5", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF860: {"length": 16, "name": "Fault record 6", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF870: {"length": 16, "name": "Fault record 7", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF880: {"length": 16, "name": "Fault record 8", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF890: {"length": 16, "name": "Fault record 9", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF8A0: {"length": 16, "name": "Fault record 10", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF8B0: {"length": 16, "name": "Fault record 11", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF8C0: {"length": 16, "name": "Fault record 12", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF8D0: {"length": 16, "name": "Fault record 13", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF8E0: {"length": 16, "name": "Fault record 14", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF8F0: {"length": 16, "name": "Fault record 15", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF900: {"length": 16, "name": "Status record 0", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF910: {"length": 16, "name": "Status record 1", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF920: {"length": 16, "name": "Status record 2", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF930: {"length": 16, "name": "Status record 3", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF940: {"length": 16, "name": "Status record 4", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF950: {"length": 16, "name": "Status record 5", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF960: {"length": 16, "name": "Status record 6", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF970: {"length": 16, "name": "Status record 7", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF980: {"length": 16, "name": "Status record 8", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF990: {"length": 16, "name": "Status record 9", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF9A0: {"length": 16, "name": "Status record 10", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF9B0: {"length": 16, "name": "Status record 11", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF9C0: {"length": 16, "name": "Status record 12", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF9D0: {"length": 16, "name": "Status record 13", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF9E0: {"length": 16, "name": "Status record 14", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xF9F0: {"length": 16, "name": "Status record 15", "access": "rw", "decoder": decoder.decode_record, "partition": "p09"},
        0xFA00: {},
        0xFA01: {},
    }
