
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-15T15:10:23+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e06eef234095d701d4a48ee34808aa5867561ad6",
 "version": "1.0.29.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
