# Generated by Django 3.2.20 on 2023-08-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名字')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='编号')),
                ('abbr', models.CharField(blank=True, default='', max_length=32, verbose_name='缩写')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ('-is_active', '-create_time'),
            },
        ),
    ]
