
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-15T23:47:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e76221f770e9cdcf40e08759a5f88a328e3db8d6",
 "version": "0.18.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
