
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-14T10:01:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f16504d02d161fdcdba3c5398ffca084aaf13a8c",
 "version": "1.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
