
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-16T10:15:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e1a54378b4fe55ffe895017e0c805a09c7e478c",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
