
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-18T08:29:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a92f61382d18cd7e84c4a424f52089c61b617e8f",
 "version": "0.4.0.post0.dev124"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
