from . import armstrong
from . import even
from . import factor
from . import fibonacci
from . import natural
from . import odd
from . import palindrome
from . import primes
from . import whole