
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-15T08:54:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b43a07763ceb7c6f44391bc11df12e14d0321189",
 "version": "1.18.4.post0.dev134"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
