# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archipelagos/common/protobuf/common/user/User.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from archipelagos.common.protobuf.common import Timestamp_pb2 as archipelagos_dot_common_dot_protobuf_dot_common_dot_Timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3archipelagos/common/protobuf/common/user/User.proto\x12(archipelagos.common.protobuf.common.user\x1a\x33\x61rchipelagos/common/protobuf/common/Timestamp.proto\"\x87\x03\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06\x61piKey\x18\x03 \x01(\t\x12\x11\n\tfirstName\x18\x04 \x01(\t\x12\x10\n\x08lastName\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12R\n\nproperties\x18\x07 \x03(\x0b\x32>.archipelagos.common.protobuf.common.user.User.PropertiesEntry\x12\x0f\n\x07\x65nabled\x18\x08 \x01(\x08\x12?\n\x07\x63reated\x18\t \x01(\x0b\x32..archipelagos.common.protobuf.common.Timestamp\x12>\n\x06\x65\x64ited\x18\n \x01(\x0b\x32..archipelagos.common.protobuf.common.Timestamp\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x35\n(archipelagos.common.protobuf.common.userB\tUserProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archipelagos.common.protobuf.common.user.User_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n(archipelagos.common.protobuf.common.userB\tUserProto'
  _USER_PROPERTIESENTRY._options = None
  _USER_PROPERTIESENTRY._serialized_options = b'8\001'
  _USER._serialized_start=151
  _USER._serialized_end=542
  _USER_PROPERTIESENTRY._serialized_start=493
  _USER_PROPERTIESENTRY._serialized_end=542
# @@protoc_insertion_point(module_scope)
