
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-11T13:28:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3dac64faeae154989222cf1a846ffb02f2322ccb",
 "version": "0.16.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
