
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-18T15:44:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f82f14e6f0826e86c05f16a088a04f109bb65842",
 "version": "4.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
