
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-15T20:17:35+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5233665b6cd72bb27f0e04404a839e30f1c6c6ea",
 "version": "1.2.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
