
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-18T09:10:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e33b23d6d3d17cce826fea841f15a2228061a0c",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
