VERSION = '1.1.4'

MARGIN = 10

DWG = None 

STYLESHEET = None

DEFAULTFONTFAMILY = 'Open Sans'
DEFAULTFONTSIZE = '10px'
DEFAULTFONTSTYLE = None
DEFAULTFONTWEIGHT = None 
DEFAULTFONTDECORATION = None   