
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-15T10:33:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d1be91cf49160126884b02a8db332b9df28b819",
 "version": "5.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
