
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-15T21:36:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "58c1de05f25c182f2ac999b1c8736fa57114f17b",
 "version": "2.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
