
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-18T09:21:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "804104162a1fb3756f4eb42acd8ed6651d413e9d",
 "version": "2.18.1b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
