# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archipelagos/common/protobuf/common/data/filestore/FileMetadataRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLarchipelagos/common/protobuf/common/data/filestore/FileMetadataRequest.proto\x12\x32\x61rchipelagos.common.protobuf.common.data.filestore\"\x8f\x01\n\x13\x46ileMetadataRequest\x12\x0e\n\x06\x61piKey\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05label\x18\x04 \x01(\t\x12\x12\n\npatternSet\x18\x05 \x01(\x08\x12\x0f\n\x07pattern\x18\x06 \x01(\t\x12\x12\n\nclientType\x18\x07 \x01(\tBN\n2archipelagos.common.protobuf.common.data.filestoreB\x18\x46ileMetadataRequestProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archipelagos.common.protobuf.common.data.filestore.FileMetadataRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n2archipelagos.common.protobuf.common.data.filestoreB\030FileMetadataRequestProto'
  _FILEMETADATAREQUEST._serialized_start=133
  _FILEMETADATAREQUEST._serialized_end=276
# @@protoc_insertion_point(module_scope)
