# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archipelagos/common/protobuf/common/data/filestore/FileStoreRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIarchipelagos/common/protobuf/common/data/filestore/FileStoreRequest.proto\x12\x32\x61rchipelagos.common.protobuf.common.data.filestore\"u\n\x10\x46ileStoreRequest\x12\x0e\n\x06\x61piKey\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05label\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x12\n\nclientType\x18\x06 \x01(\tBK\n2archipelagos.common.protobuf.common.data.filestoreB\x15\x46ileStoreRequestProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archipelagos.common.protobuf.common.data.filestore.FileStoreRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n2archipelagos.common.protobuf.common.data.filestoreB\025FileStoreRequestProto'
  _FILESTOREREQUEST._serialized_start=129
  _FILESTOREREQUEST._serialized_end=246
# @@protoc_insertion_point(module_scope)
