# coding: utf-8

"""
    Traveler API

    The API that provides access to Traveler data.  # noqa: E501

    The version of the OpenAPI document: APS-1.6.4
    Contact: djarosz@anl.gov
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from travelerApi.configuration import Configuration


class TravelerDiscrepancy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'discrepancy_form': 'DiscrepancyForm',
        'discrepancy_logs': 'list[DiscrepancyLog]'
    }

    attribute_map = {
        'discrepancy_form': 'discrepancyForm',
        'discrepancy_logs': 'discrepancyLogs'
    }

    def __init__(self, discrepancy_form=None, discrepancy_logs=None, local_vars_configuration=None):  # noqa: E501
        """TravelerDiscrepancy - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._discrepancy_form = None
        self._discrepancy_logs = None
        self.discriminator = None

        if discrepancy_form is not None:
            self.discrepancy_form = discrepancy_form
        if discrepancy_logs is not None:
            self.discrepancy_logs = discrepancy_logs

    @property
    def discrepancy_form(self):
        """Gets the discrepancy_form of this TravelerDiscrepancy.  # noqa: E501


        :return: The discrepancy_form of this TravelerDiscrepancy.  # noqa: E501
        :rtype: DiscrepancyForm
        """
        return self._discrepancy_form

    @discrepancy_form.setter
    def discrepancy_form(self, discrepancy_form):
        """Sets the discrepancy_form of this TravelerDiscrepancy.


        :param discrepancy_form: The discrepancy_form of this TravelerDiscrepancy.  # noqa: E501
        :type: DiscrepancyForm
        """

        self._discrepancy_form = discrepancy_form

    @property
    def discrepancy_logs(self):
        """Gets the discrepancy_logs of this TravelerDiscrepancy.  # noqa: E501


        :return: The discrepancy_logs of this TravelerDiscrepancy.  # noqa: E501
        :rtype: list[DiscrepancyLog]
        """
        return self._discrepancy_logs

    @discrepancy_logs.setter
    def discrepancy_logs(self, discrepancy_logs):
        """Sets the discrepancy_logs of this TravelerDiscrepancy.


        :param discrepancy_logs: The discrepancy_logs of this TravelerDiscrepancy.  # noqa: E501
        :type: list[DiscrepancyLog]
        """

        self._discrepancy_logs = discrepancy_logs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TravelerDiscrepancy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TravelerDiscrepancy):
            return True

        return self.to_dict() != other.to_dict()
