# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import permissionmessages_pb2 as permissionmessages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btoken.proto\x12\x05token\x1a\x18permissionmessages.proto\"\xc7\x01\n\x19_GenerateAuthAcornRequest\x12\x39\n\x07\x65xpires\x18\x01 \x01(\x0b\x32(.token._GenerateAuthAcornRequest.Expires\x12\x12\n\nauth_token\x18\x02 \x01(\t\x12\x35\n\x0bpermissions\x18\x03 \x01(\x0b\x32 .permission_messages.Permissions\x1a$\n\x07\x45xpires\x12\x19\n\x11valid_for_seconds\x18\x01 \x01(\r\"T\n\x1a_GenerateAuthAcornResponse\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x13\n\x0bvalid_until\x18\x03 \x01(\x04\x32\x63\n\x05Token\x12Z\n\x11GenerateAuthAcorn\x12 .token._GenerateAuthAcornRequest\x1a!.token._GenerateAuthAcornResponse\"\x00\x42\x43\n\rmomento.tokenP\x01Z0github.com/momentohq/client-sdk-go;client_sdk_gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'token_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rmomento.tokenP\001Z0github.com/momentohq/client-sdk-go;client_sdk_go'
  __GENERATEAUTHACORNREQUEST._serialized_start=49
  __GENERATEAUTHACORNREQUEST._serialized_end=248
  __GENERATEAUTHACORNREQUEST_EXPIRES._serialized_start=212
  __GENERATEAUTHACORNREQUEST_EXPIRES._serialized_end=248
  __GENERATEAUTHACORNRESPONSE._serialized_start=250
  __GENERATEAUTHACORNRESPONSE._serialized_end=334
  _TOKEN._serialized_start=336
  _TOKEN._serialized_end=435
# @@protoc_insertion_point(module_scope)
