# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archipelagos/common/protobuf/common/data/collection/Collection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from archipelagos.common.protobuf.common.data.collection import CollectionMetadata_pb2 as archipelagos_dot_common_dot_protobuf_dot_common_dot_data_dot_collection_dot_CollectionMetadata__pb2
from archipelagos.common.protobuf.common.data.collection import CollectionData_pb2 as archipelagos_dot_common_dot_protobuf_dot_common_dot_data_dot_collection_dot_CollectionData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDarchipelagos/common/protobuf/common/data/collection/Collection.proto\x12\x33\x61rchipelagos.common.protobuf.common.data.collection\x1aLarchipelagos/common/protobuf/common/data/collection/CollectionMetadata.proto\x1aHarchipelagos/common/protobuf/common/data/collection/CollectionData.proto\"\xba\x01\n\nCollection\x12Y\n\x08metadata\x18\x01 \x01(\x0b\x32G.archipelagos.common.protobuf.common.data.collection.CollectionMetadata\x12Q\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x43.archipelagos.common.protobuf.common.data.collection.CollectionDataBF\n3archipelagos.common.protobuf.common.data.collectionB\x0f\x43ollectionProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archipelagos.common.protobuf.common.data.collection.Collection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n3archipelagos.common.protobuf.common.data.collectionB\017CollectionProto'
  _COLLECTION._serialized_start=278
  _COLLECTION._serialized_end=464
# @@protoc_insertion_point(module_scope)
