#!/usr/bin/env python
# This script has been automatically generated by AbiPy.
from __future__ import annotations

import numpy as np
import pandas as pd

if False:
    import seaborn as sns
    sns.set(context="paper", style='darkgrid', palette='deep',
            font='sans-serif', font_scale=0.8, color_codes=False, rc=None)


from abipy.ml.relax_scanner import RelaxScanner, Entries
from abipy.tools.printing import print_dataframe

data = Entries.merge_from_topdir(".").get_data()
print_dataframe(data.df)
#data.histplot()
data.search_enediff_dist(1e-5, 2, verbose=1)
