# Generated by Django 3.2.11 on 2022-06-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_zb_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsite',
            name='slug',
            field=models.SlugField(unique='True', verbose_name='Slug'),
        ),
    ]
