# Generated by Django 3.2.11 on 2022-06-01 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_zb_organizations', '0009_auto_20220601_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='image',
            new_name='picture',
        ),
    ]
