# Generated by Django 4.0 on 2022-09-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leave', '0010_leave_de_obs_leave_hr_obs_leave_unit_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='de_obs',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='hr_obs',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='unit_obs',
        ),
        migrations.CreateModel(
            name='LeaveUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Lae', 'Lae')], max_length=3, null=True, verbose_name='Observasaun')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Rajaun')),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveunit', to='leave.leave')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
