# Generated by Django 4.0 on 2022-09-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_leave_is_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavecount',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='leavecount',
            name='hashed',
        ),
        migrations.RemoveField(
            model_name='leavecount',
            name='user',
        ),
        migrations.AlterField(
            model_name='leavecount',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Balansu'),
        ),
    ]
