# Generated by Django 3.2 on 2022-12-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0029_leavedep'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='dep_confirm',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='dep_send',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
