# Generated by Django 3.2 on 2022-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0032_leave_dep_send_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='pr_confirm',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
