# Generated by Django 3.2 on 2022-12-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0038_alter_leavetype_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
