# Generated by Django 3.2 on 2022-12-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0044_leavecount_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='start_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Balance Start'),
        ),
        migrations.AlterField(
            model_name='leavecount',
            name='balance_carry',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Balansu Carry Forward'),
        ),
    ]
