# Generated by Django 3.2 on 2022-12-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0050_leavecount_total_balance_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecount',
            name='taken',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Taken'),
        ),
    ]
