# Generated by Django 3.2 on 2023-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0065_leave_vice_send_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='pr_notify',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
