# Generated by Django 3.2 on 2023-02-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0068_auto_20230202_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_special',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
