# Generated by Django 3.2 on 2023-02-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0069_leave_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_create_by_hr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
