
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-16T16:58:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d1d6507e863a32d68e32d5100562e11d298a694",
 "version": "0.1.3.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
