
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-01T09:40:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0258963ea037821fbaece910d6bc23fc93ae0ba3",
 "version": "0.0.8.dev20230815"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
