class RuobrExcetion(Exception):
  ...

class AuthorizationError(RuobrExcetion):
  ...
  
class IncorrectDateError(RuobrExcetion):
  ...

class EmptyDateError(RuobrExcetion):
  ...

class RequestError(RuobrExcetion):
  ...
  
class DateNotFoundError(RuobrExcetion):
  ...