# Generated by Django 3.2.11 on 2022-06-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_zb_organizations', '0020_organization_initials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='initials',
            new_name='initial',
        ),
    ]
