from . import account_invoice_service
from . import bank_from_iban_getter
from . import contract_one_shot_service
from . import contract_one_shot_process
from . import contract_contract_service
from . import contract_email_change_service
from . import contract_iban_change_process
from . import contract_change_tariff_service
from . import contract_change_tariff_process
from . import crm_lead_service
from . import discovery_channel_service
from . import partner_email_change_service
from . import product_catalog_service
from . import provider_service
from . import res_partner_service
from . import subscription_request_service
from . import vat_normalizer
