# Generated by Django 2.2.28 on 2023-03-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_application', '0002_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='api_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
