
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-16T11:15:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2062f4bb7636879b5c505cc5c470bbf07b1fbefa",
 "version": "2.9.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
