
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-14T09:55:05-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "055cbd9272c9005286a58e3ac0ac95da7ca6673f",
 "version": "v0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
