
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-14T16:29:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c87905065e9180b76897856da818c00fce897b48",
 "version": "1.18.4.post0.dev132"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
