# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archipelagos/common/protobuf/common/data/collection/CollectionData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from archipelagos.common.protobuf.common.data import DataEntry_pb2 as archipelagos_dot_common_dot_protobuf_dot_common_dot_data_dot_DataEntry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHarchipelagos/common/protobuf/common/data/collection/CollectionData.proto\x12\x33\x61rchipelagos.common.protobuf.common.data.collection\x1a\x38\x61rchipelagos/common/protobuf/common/data/DataEntry.proto\"`\n\x0e\x43ollectionData\x12\x0b\n\x03ids\x18\x01 \x03(\t\x12\x41\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x33.archipelagos.common.protobuf.common.data.DataEntryBJ\n3archipelagos.common.protobuf.common.data.collectionB\x13\x43ollectionDataProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archipelagos.common.protobuf.common.data.collection.CollectionData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n3archipelagos.common.protobuf.common.data.collectionB\023CollectionDataProto'
  _COLLECTIONDATA._serialized_start=187
  _COLLECTIONDATA._serialized_end=283
# @@protoc_insertion_point(module_scope)
