# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archipelagos/common/protobuf/common/data/timeseries/TimeSeries.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from archipelagos.common.protobuf.common.data.timeseries import TimeSeriesMetadata_pb2 as archipelagos_dot_common_dot_protobuf_dot_common_dot_data_dot_timeseries_dot_TimeSeriesMetadata__pb2
from archipelagos.common.protobuf.common.data.timeseries import TimeSeriesData_pb2 as archipelagos_dot_common_dot_protobuf_dot_common_dot_data_dot_timeseries_dot_TimeSeriesData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDarchipelagos/common/protobuf/common/data/timeseries/TimeSeries.proto\x12\x33\x61rchipelagos.common.protobuf.common.data.timeseries\x1aLarchipelagos/common/protobuf/common/data/timeseries/TimeSeriesMetadata.proto\x1aHarchipelagos/common/protobuf/common/data/timeseries/TimeSeriesData.proto\"\xba\x01\n\nTimeSeries\x12Y\n\x08metadata\x18\x01 \x01(\x0b\x32G.archipelagos.common.protobuf.common.data.timeseries.TimeSeriesMetadata\x12Q\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x43.archipelagos.common.protobuf.common.data.timeseries.TimeSeriesDataBF\n3archipelagos.common.protobuf.common.data.timeseriesB\x0fTimeSeriesProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archipelagos.common.protobuf.common.data.timeseries.TimeSeries_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n3archipelagos.common.protobuf.common.data.timeseriesB\017TimeSeriesProto'
  _TIMESERIES._serialized_start=278
  _TIMESERIES._serialized_end=464
# @@protoc_insertion_point(module_scope)
