EFO = "https://github.com/EBISPOT/efo/releases/download/current/efo.owl"
EFO_LOCAL = "/Users/rsgoncalves/Documents/Workspace/text2term/test/ontologies/efo.owl"
ORDO = "/Users/rsgoncalves/Documents/Harvard/ontologies/ordo.owl"
HP = "/Users/rsgoncalves/Documents/Harvard/ontologies/hp.owl"
MONDO = "/Users/rsgoncalves/Documents/Harvard/ontologies/mondo.owl"
DOID = "/Users/rsgoncalves/Documents/Harvard/ontologies/doid.owl"
OMIT = "/Users/rsgoncalves/Documents/Harvard/ontologies/omit.owl"
PROT = "/Users/rsgoncalves/Documents/Harvard/ontologies/pro_nonreasoned.owl"
OAE = "/Users/rsgoncalves/Documents/Harvard/ontologies/oae.owl"
NCIT = "/Users/rsgoncalves/Documents/Harvard/ontologies/ncit.owl"
CHEBI = ""
MESH = "/Users/rsgoncalves/Documents/Harvard/ontologies/mesh.owl"

TEST = "/Users/rsgoncalves/Documents/Workspace/text2term/test/ontologies/test.owl"
