#ifndef GRAPES_GRAPES_CGRAPH_MACROS_H_
#define GRAPES_GRAPES_CGRAPH_MACROS_H_

#define GRAPES_FALSE 0
#define GRAPES_TRUE 1
#define GRAPES_RED 0
#define GRAPES_BLUE 1
#define GRAPES_NO_COLOR -1

#endif  // GRAPES_GRAPES_CGRAPH_MACROS_H_