# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import pprint
import re  # noqa: F401

from ..configuration import Configuration


class AnalysisSpec(object):
    """
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'data_query': 'str',
    }

    attribute_map = {
        'name': 'name',
        'data_query': 'data_query',
    }

    def __init__(self, name=None, data_query='*', local_vars_configuration=None):  # noqa: E501
        """AnalysisSpec - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._data_query = None
        self.discriminator = None

        self.name = name
        self.data_query = data_query

    @property
    def name(self):
        """
        Name of analysis.

        :return: The name of this AnalysisSpec. 
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Name of analysis.

        :param name: The name of this AnalysisSpec.
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def data_query(self):
        """
        Lucene query string used to retrieve entities to analyze.

        :return: The data_query of this AnalysisSpec. 
        :rtype: str
        """
        return self._data_query

    @data_query.setter
    def data_query(self, data_query):
        """
        Lucene query string used to retrieve entities to analyze.

        :param data_query: The data_query of this AnalysisSpec.
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and data_query is None:  # noqa: E501
            raise ValueError("Invalid value for `data_query`, must not be `None`")  # noqa: E501

        self._data_query = data_query

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnalysisSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AnalysisSpec):
            return True

        return self.to_dict() != other.to_dict()
