# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archipelagos/common/protobuf/common/data/filestore/FileStoreMetadataResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from archipelagos.common.protobuf.common.data.filestore import FileStoreMetadata_pb2 as archipelagos_dot_common_dot_protobuf_dot_common_dot_data_dot_filestore_dot_FileStoreMetadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRarchipelagos/common/protobuf/common/data/filestore/FileStoreMetadataResponse.proto\x12\x32\x61rchipelagos.common.protobuf.common.data.filestore\x1aJarchipelagos/common/protobuf/common/data/filestore/FileStoreMetadata.proto\"\xb7\x01\n\x19\x46ileStoreMetadataResponse\x12\x18\n\x10\x65rrorHasOccurred\x18\x01 \x01(\x08\x12W\n\x08metadata\x18\x02 \x01(\x0b\x32\x45.archipelagos.common.protobuf.common.data.filestore.FileStoreMetadata\x12\x11\n\terrorCode\x18\x03 \x01(\x05\x12\x14\n\x0c\x65rrorMessage\x18\x04 \x01(\tBT\n2archipelagos.common.protobuf.common.data.filestoreB\x1e\x46ileStoreMetadataResponseProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archipelagos.common.protobuf.common.data.filestore.FileStoreMetadataResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n2archipelagos.common.protobuf.common.data.filestoreB\036FileStoreMetadataResponseProto'
  _FILESTOREMETADATARESPONSE._serialized_start=215
  _FILESTOREMETADATARESPONSE._serialized_end=398
# @@protoc_insertion_point(module_scope)
