# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2023-02-17T08:30:07+00:00

from __future__ import annotations

import uuid
from pydantic import BaseModel, Extra, Field, constr


class Meta(BaseModel):
    class Config:
        extra = Extra.allow

    id: uuid.UUID | None = None
    trace: str | None = None
    redirect: constr(regex=r'^[0-9a-zA-Z_-]+$', min_length=1, max_length=200) | None = None
    icon: str | None = None
    tag: list[constr(min_length=2, max_length=20)] | None = None
    tag_by_user: list[constr(min_length=2, max_length=20)] | None = None
    name_by_user: constr(max_length=100) | None = None


class FileItem(BaseModel):
    class Config:
        extra = Extra.allow

    id: uuid.UUID | None = None


class EmailSend(BaseModel):
    class Config:
        extra = Extra.allow

    meta: Meta | None = Field(None, title='meta-2.1')
    to: uuid.UUID | constr(regex=r'^\S+@\S+\.\S+$') | None = None
    html: str
    subject: str
    from_: str = Field(..., alias='from')
    file: list[FileItem] | None = None
