# coding: utf-8

"""
    MeMaS DP APIs

    This is the Data Plane APIs for MeMaS (Memory Management Service).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: max.yu@memas.ai
    Generated by: https://openapi-generator.tech
"""

from memas_client.paths.dp_recollect.post import Recollect
from memas_client.paths.dp_remember.post import Remember


class DpApi(
    Recollect,
    Remember,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
