# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2023-02-17T08:31:10+00:00

from __future__ import annotations

import uuid
from typing import Any
from pydantic import BaseModel, Extra, constr


class MetaItem(BaseModel):
    class Config:
        extra = Extra.allow

    id: uuid.UUID | None = None
    trace: str | None = None
    redirect: constr(regex=r'^[0-9a-zA-Z_-]+$', min_length=1, max_length=200) | None = None
    icon: str | None = None
    tag: list[constr(min_length=2, max_length=20)] | None = None
    tag_by_user: list[constr(min_length=2, max_length=20)] | None = None
    name_by_user: constr(max_length=100) | None = None


class Filter(BaseModel):
    class Config:
        extra = Extra.forbid

    meta:  MetaItem | None = None
    name: str | None = None
    type: str | None = None
    parser: dict[str, Any] | None = None
    alert: dict[str, Any] | None = None
    repeat: dict[str, Any] | None = None
    parsed: Any | None = None
