VERSION_YEAR = 2023
VERSION_MONTH = int('08')
VERSION_DAY = int('15')
VERSION_HOUR = int('19')
VERSION_MINUTE = int('34')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202308151934
version_date = '2023/08/15 19:34'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
