# Generated by Django 4.0 on 2022-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leavedelegate_is_confirm2'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
