# Generated by Django 4.0 on 2022-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_alter_leavedelegate_leave_alter_leaveunit_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_finish',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
