# Generated by Django 4.0 on 2022-09-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0018_alter_leavecount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='s_is_delegate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
