# Generated by Django 3.2 on 2022-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0025_auto_20221210_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
