# Generated by Django 3.2 on 2022-12-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0030_auto_20221211_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_update',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
