# Generated by Django 3.2 on 2022-12-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0031_leave_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='dep_send_pr',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
