# Generated by Django 3.2 on 2022-12-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0035_leave_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='unit_send_pr',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
