# Generated by Django 3.2 on 2022-12-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0040_alter_leavecount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecount',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
    ]
