# Generated by Django 3.2 on 2022-12-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0042_alter_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecount',
            name='balance_carry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Balansu Carry Forward'),
        ),
    ]
