# Generated by Django 3.2 on 2022-12-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0043_leavecount_balance_carry'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecount',
            name='taken',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
    ]
