# Generated by Django 3.2 on 2022-12-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0052_leavecount_prov_total_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecount',
            name='total_taken',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Total Taken'),
        ),
    ]
