# Generated by Django 3.2 on 2023-01-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0062_leavehr_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
