# Generated by Django 3.2 on 2023-01-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0064_leave_pr_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='vice_send_pr',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
