# Generated by Django 3.2 on 2023-01-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0066_leave_pr_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_send_to_div',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
