# Generated by Django 3.2 on 2023-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0071_auto_20230313_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_time_status',
            field=models.CharField(blank=True, choices=[('12', '12'), ('17', '17')], max_length=15, null=True, verbose_name='Horas Remata Licensa'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_time_status',
            field=models.CharField(blank=True, choices=[('08', '08'), ('13', '13')], max_length=15, null=True, verbose_name='Horas Hahu Licensa'),
        ),
    ]
