# Generated by Django 3.2 on 2023-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0073_auto_20230313_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_time_status',
            field=models.CharField(blank=True, choices=[('12:00', '12:00'), ('17:00', '17:00')], max_length=15, null=True, verbose_name='Horas Remata Licensa'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_time_status',
            field=models.CharField(blank=True, choices=[('08:00', '08:00'), ('13:00', '13:00')], max_length=15, null=True, verbose_name='Horas Hahu Licensa'),
        ),
    ]
