# coding: utf-8

"""
    Traveler API

    The API that provides access to Traveler data.  # noqa: E501

    The version of the OpenAPI document: APS-1.6.4
    Contact: djarosz@anl.gov
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from travelerApi.configuration import Configuration


class BinderCreateOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'binder_title': 'str',
        'description': 'str',
        'user_name': 'str'
    }

    attribute_map = {
        'binder_title': 'binderTitle',
        'description': 'description',
        'user_name': 'userName'
    }

    def __init__(self, binder_title=None, description=None, user_name=None, local_vars_configuration=None):  # noqa: E501
        """BinderCreateOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._binder_title = None
        self._description = None
        self._user_name = None
        self.discriminator = None

        if binder_title is not None:
            self.binder_title = binder_title
        if description is not None:
            self.description = description
        if user_name is not None:
            self.user_name = user_name

    @property
    def binder_title(self):
        """Gets the binder_title of this BinderCreateOptions.  # noqa: E501


        :return: The binder_title of this BinderCreateOptions.  # noqa: E501
        :rtype: str
        """
        return self._binder_title

    @binder_title.setter
    def binder_title(self, binder_title):
        """Sets the binder_title of this BinderCreateOptions.


        :param binder_title: The binder_title of this BinderCreateOptions.  # noqa: E501
        :type: str
        """

        self._binder_title = binder_title

    @property
    def description(self):
        """Gets the description of this BinderCreateOptions.  # noqa: E501


        :return: The description of this BinderCreateOptions.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BinderCreateOptions.


        :param description: The description of this BinderCreateOptions.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def user_name(self):
        """Gets the user_name of this BinderCreateOptions.  # noqa: E501


        :return: The user_name of this BinderCreateOptions.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this BinderCreateOptions.


        :param user_name: The user_name of this BinderCreateOptions.  # noqa: E501
        :type: str
        """

        self._user_name = user_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BinderCreateOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BinderCreateOptions):
            return True

        return self.to_dict() != other.to_dict()
