# coding: utf-8

"""
    Traveler API

    The API that provides access to Traveler data.  # noqa: E501

    The version of the OpenAPI document: APS-1.6.4
    Contact: djarosz@anl.gov
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from travelerApi.configuration import Configuration


class TravelerUpdateOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'user_name': 'str',
        'title': 'str',
        'description': 'str',
        'deadline': 'datetime',
        'status': 'float',
        'devices': 'list[str]'
    }

    attribute_map = {
        'user_name': 'userName',
        'title': 'title',
        'description': 'description',
        'deadline': 'deadline',
        'status': 'status',
        'devices': 'devices'
    }

    def __init__(self, user_name=None, title=None, description=None, deadline=None, status=None, devices=None, local_vars_configuration=None):  # noqa: E501
        """TravelerUpdateOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._user_name = None
        self._title = None
        self._description = None
        self._deadline = None
        self._status = None
        self._devices = None
        self.discriminator = None

        if user_name is not None:
            self.user_name = user_name
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if deadline is not None:
            self.deadline = deadline
        if status is not None:
            self.status = status
        if devices is not None:
            self.devices = devices

    @property
    def user_name(self):
        """Gets the user_name of this TravelerUpdateOptions.  # noqa: E501


        :return: The user_name of this TravelerUpdateOptions.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this TravelerUpdateOptions.


        :param user_name: The user_name of this TravelerUpdateOptions.  # noqa: E501
        :type: str
        """

        self._user_name = user_name

    @property
    def title(self):
        """Gets the title of this TravelerUpdateOptions.  # noqa: E501


        :return: The title of this TravelerUpdateOptions.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this TravelerUpdateOptions.


        :param title: The title of this TravelerUpdateOptions.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this TravelerUpdateOptions.  # noqa: E501


        :return: The description of this TravelerUpdateOptions.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TravelerUpdateOptions.


        :param description: The description of this TravelerUpdateOptions.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def deadline(self):
        """Gets the deadline of this TravelerUpdateOptions.  # noqa: E501


        :return: The deadline of this TravelerUpdateOptions.  # noqa: E501
        :rtype: datetime
        """
        return self._deadline

    @deadline.setter
    def deadline(self, deadline):
        """Sets the deadline of this TravelerUpdateOptions.


        :param deadline: The deadline of this TravelerUpdateOptions.  # noqa: E501
        :type: datetime
        """

        self._deadline = deadline

    @property
    def status(self):
        """Gets the status of this TravelerUpdateOptions.  # noqa: E501


        :return: The status of this TravelerUpdateOptions.  # noqa: E501
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TravelerUpdateOptions.


        :param status: The status of this TravelerUpdateOptions.  # noqa: E501
        :type: float
        """

        self._status = status

    @property
    def devices(self):
        """Gets the devices of this TravelerUpdateOptions.  # noqa: E501


        :return: The devices of this TravelerUpdateOptions.  # noqa: E501
        :rtype: list[str]
        """
        return self._devices

    @devices.setter
    def devices(self, devices):
        """Sets the devices of this TravelerUpdateOptions.


        :param devices: The devices of this TravelerUpdateOptions.  # noqa: E501
        :type: list[str]
        """

        self._devices = devices

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TravelerUpdateOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TravelerUpdateOptions):
            return True

        return self.to_dict() != other.to_dict()
